import { type Gig, type User, type Location } from './types';

export const ADDIS_LOCATIONS: Location[] = [
  'Bole',
  'Yeka',
  'Kirkos',
  'Addis Ketema',
  'Lideta',
  'Akaki-Kality',
  'Nifas Silk-Lafto',
  'Kolfe Keranio',
  'Gulele',
  'Semt-Legedir',
];

export const USERS: User[] = [
  {
    id: 'user-1',
    email: 'client@addisgigfind.com',
    name: 'Abebe Kebede',
    role: 'client',
    avatar_url: null,
    phone: '+251911234567',
    location: 'Bole',
    is_verified: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    email: 'freelancer@addisgigfind.com',
    name: 'Tigist Haile',
    role: 'freelancer',
    avatar_url: null,
    phone: '+251922345678',
    location: 'Yeka',
    is_verified: true,
    created_at: '2025-01-05T00:00:00Z',
  },
  {
    id: 'user-3',
    email: 'admin@addisgigfind.com',
    name: 'Daniel Asrat',
    role: 'admin',
    avatar_url: null,
    phone: '+251933456789',
    location: 'Kirkos',
    is_verified: true,
    created_at: '2024-12-01T00:00:00Z',
  },
];

export const GIGS: Gig[] = [
  {
    id: 'gig-1',
    title: 'Website Development for Restaurant',
    description: 'Need a modern website for a traditional Ethiopian restaurant in Bole. Should include menu display, online reservation system, and mobile responsiveness.',
    client_id: 'user-1',
    budget: 15000,
    location: 'Bole',
    category: 'Web Development',
    status: 'open',
    deadline: '2026-02-15T23:59:59Z',
    created_at: '2026-01-20T10:00:00Z',
    applicant_count: 3,
  },
  {
    id: 'gig-2',
    title: 'Logo Design for Tech Startup',
    description: 'Looking for a professional logo for our fintech startup. Should convey trust and innovation. Vector format required.',
    client_id: 'user-1',
    budget: 5000,
    location: 'Yeka',
    category: 'Graphic Design',
    status: 'open',
    deadline: '2026-02-01T23:59:59Z',
    created_at: '2026-01-18T14:30:00Z',
    applicant_count: 7,
  },
  {
    id: 'gig-3',
    title: 'Amharic Content Writing',
    description: 'Need SEO-optimized blog posts about Ethiopian coffee culture. 10 articles, 1000 words each.',
    client_id: 'user-1',
    budget: 8000,
    location: 'Kirkos',
    category: 'Content Writing',
    status: 'open',
    deadline: '2026-02-28T23:59:59Z',
    created_at: '2026-01-22T09:00:00Z',
    applicant_count: 2,
  },
  {
    id: 'gig-4',
    title: 'Mobile App UI/UX Design',
    description: 'Design a user-friendly interface for a ride-hailing app similar to Ride. Focus on simplicity and accessibility.',
    client_id: 'user-1',
    budget: 25000,
    location: 'Addis Ketema',
    category: 'UI/UX Design',
    status: 'in_progress',
    deadline: '2026-03-15T23:59:59Z',
    created_at: '2026-01-10T16:00:00Z',
    applicant_count: 5,
  },
  {
    id: 'gig-5',
    title: 'Social Media Marketing Campaign',
    description: 'Run a 30-day Instagram marketing campaign for a new fashion boutique. Must include content creation and engagement strategy.',
    client_id: 'user-1',
    budget: 12000,
    location: 'Lideta',
    category: 'Digital Marketing',
    status: 'open',
    deadline: '2026-02-20T23:59:59Z',
    created_at: '2026-01-25T11:00:00Z',
    applicant_count: 4,
  },
];

export const CATEGORIES = [
  'Web Development',
  'Graphic Design',
  'Content Writing',
  'UI/UX Design',
  'Digital Marketing',
  'Mobile Development',
  'Video Editing',
  'Translation',
  'Data Entry',
  'Other',
] as const;
